version: 2
jobs:
  build:
    docker:
      - image: ishiko/gcc-ishiko-cpp-build-prerequisites:0.1.0
    steps:
      - run:
          name: "Set ISHIKO_CPP environment variable and create workspace directory"
          command: mkdir -p /projects/ishiko/cpp && echo 'export ISHIKO_CPP="/projects/ishiko/cpp"' >> $BASH_ENV
      - run:
          name: "Checkout Ishiko-cpp/botan dependency"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/botan.git && cd botan && git checkout 2.17.3
      - checkout:
          path: /projects/ishiko/cpp/crypto
      - run:
          name: "Build: Ishiko-cpp/botan dependency"
          command: cd /projects/ishiko/cpp/botan && python3 configure.py --prefix=/projects/ishiko/cpp/botan --disable-shared-library && make && make install && echo 'export ISHIKO_CPP_THIRD_PARTY_BOTAN="/projects/ishiko/cpp/botan"' >> $BASH_ENV
      - run:
          name: Build
          command: cd /Ishiko-cpp/Crypto/Makefiles/GNUmakefile && make
      - run:
          name: "Checkout Ishiko-cpp/Platform test dependency"
          command: cd /Ishiko-cpp && git clone https://github.com/Ishiko-cpp/Platform.git
      - run:
          name: "Checkout Ishiko-cpp/Errors test dependency"
          command: cd /Ishiko-cpp && git clone https://github.com/Ishiko-cpp/Errors.git
      - run:
          name: "Checkout Ishiko-cpp/Text test dependency"
          command: cd /Ishiko-cpp && git clone https://github.com/Ishiko-cpp/Text.git
      - run:
          name: "Checkout Ishiko-cpp/Process test dependency"
          command: cd /Ishiko-cpp && git clone https://github.com/Ishiko-cpp/Process.git
      - run:
          name: "Checkout Ishiko-cpp/TestFramework test dependency"
          command: cd /Ishiko-cpp && git clone https://github.com/Ishiko-cpp/TestFramework.git
      - run:
          name: "Build Ishiko-cpp/Platform test dependency"
          command: cd /Ishiko-cpp/Platform/Makefiles/GNUmakefile && make
      - run:
          name: "Build Ishiko-cpp/Errors test dependency"
          command: cd /Ishiko-cpp/Errors/Makefiles/GNUmakefile && make
      - run:
          name: "Build Ishiko-cpp/Text test dependency"
          command: cd /Ishiko-cpp/Text/Makefiles/GNUmakefile && make
      - run:
          name: "Build Ishiko-cpp/Process test dependency"
          command: cd /Ishiko-cpp/Process/Makefiles/GNUmakefile && make
      - run:
          name: "Build Ishiko-cpp/TestFramework test dependency"
          command: cd /Ishiko-cpp/TestFramework/Core/Makefiles/GNUmakefile && make
      - run:
          name: Test build
          command: cd /Ishiko-cpp/Crypto/Tests/Makefiles/GNUmakefile && make
      - run:
          name: Run the tests
          command: cd /Ishiko-cpp/Crypto/Tests/Makefiles/GNUmakefile && ./IshikoCryptoTests
workflows:
  version: 2
  continuous_build:
    jobs:
      - build
  weekly_build:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 8 * * 0"
          filters:
            branches:
              only:
                 - main
